// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package raft.server.proto;

public interface LogEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:raft.server.proto.LogEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 index = 1;</code>
   */
  long getIndex();

  /**
   * <code>optional int64 term = 2;</code>
   */
  long getTerm();

  /**
   * <code>optional bytes data = 3;</code>
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>optional .raft.server.proto.LogEntry.EntryType type = 4;</code>
   */
  int getTypeValue();
  /**
   * <code>optional .raft.server.proto.LogEntry.EntryType type = 4;</code>
   */
  raft.server.proto.LogEntry.EntryType getType();
}
