// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package raft.server.proto;

public interface LogEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:raft.server.proto.LogEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 index = 1;</code>
   */
  int getIndex();

  /**
   * <code>int32 term = 2;</code>
   */
  int getTerm();

  /**
   * <code>bytes data = 3;</code>
   */
  com.google.protobuf.ByteString getData();
}
