// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package raft.server.proto;

/**
 * Protobuf type {@code raft.server.proto.PBRaftPersistentMeta}
 */
public  final class PBRaftPersistentMeta extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:raft.server.proto.PBRaftPersistentMeta)
    PBRaftPersistentMetaOrBuilder {
  // Use PBRaftPersistentMeta.newBuilder() to construct.
  private PBRaftPersistentMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PBRaftPersistentMeta() {
    term_ = 0;
    votedFor_ = "";
    commitIndex_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private PBRaftPersistentMeta(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            term_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            votedFor_ = s;
            break;
          }
          case 24: {

            commitIndex_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return raft.server.proto.Commands.internal_static_raft_server_proto_PBRaftPersistentMeta_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return raft.server.proto.Commands.internal_static_raft_server_proto_PBRaftPersistentMeta_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            raft.server.proto.PBRaftPersistentMeta.class, raft.server.proto.PBRaftPersistentMeta.Builder.class);
  }

  public static final int TERM_FIELD_NUMBER = 1;
  private int term_;
  /**
   * <code>optional int32 term = 1;</code>
   */
  public int getTerm() {
    return term_;
  }

  public static final int VOTEDFOR_FIELD_NUMBER = 2;
  private volatile java.lang.Object votedFor_;
  /**
   * <code>optional string votedFor = 2;</code>
   */
  public java.lang.String getVotedFor() {
    java.lang.Object ref = votedFor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      votedFor_ = s;
      return s;
    }
  }
  /**
   * <code>optional string votedFor = 2;</code>
   */
  public com.google.protobuf.ByteString
      getVotedForBytes() {
    java.lang.Object ref = votedFor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      votedFor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMITINDEX_FIELD_NUMBER = 3;
  private int commitIndex_;
  /**
   * <code>optional int32 commitIndex = 3;</code>
   */
  public int getCommitIndex() {
    return commitIndex_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (term_ != 0) {
      output.writeInt32(1, term_);
    }
    if (!getVotedForBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, votedFor_);
    }
    if (commitIndex_ != 0) {
      output.writeInt32(3, commitIndex_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (term_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, term_);
    }
    if (!getVotedForBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, votedFor_);
    }
    if (commitIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, commitIndex_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof raft.server.proto.PBRaftPersistentMeta)) {
      return super.equals(obj);
    }
    raft.server.proto.PBRaftPersistentMeta other = (raft.server.proto.PBRaftPersistentMeta) obj;

    boolean result = true;
    result = result && (getTerm()
        == other.getTerm());
    result = result && getVotedFor()
        .equals(other.getVotedFor());
    result = result && (getCommitIndex()
        == other.getCommitIndex());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + getTerm();
    hash = (37 * hash) + VOTEDFOR_FIELD_NUMBER;
    hash = (53 * hash) + getVotedFor().hashCode();
    hash = (37 * hash) + COMMITINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getCommitIndex();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static raft.server.proto.PBRaftPersistentMeta parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static raft.server.proto.PBRaftPersistentMeta parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static raft.server.proto.PBRaftPersistentMeta parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static raft.server.proto.PBRaftPersistentMeta parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static raft.server.proto.PBRaftPersistentMeta parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static raft.server.proto.PBRaftPersistentMeta parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static raft.server.proto.PBRaftPersistentMeta parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static raft.server.proto.PBRaftPersistentMeta parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static raft.server.proto.PBRaftPersistentMeta parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static raft.server.proto.PBRaftPersistentMeta parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(raft.server.proto.PBRaftPersistentMeta prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code raft.server.proto.PBRaftPersistentMeta}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:raft.server.proto.PBRaftPersistentMeta)
      raft.server.proto.PBRaftPersistentMetaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return raft.server.proto.Commands.internal_static_raft_server_proto_PBRaftPersistentMeta_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return raft.server.proto.Commands.internal_static_raft_server_proto_PBRaftPersistentMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              raft.server.proto.PBRaftPersistentMeta.class, raft.server.proto.PBRaftPersistentMeta.Builder.class);
    }

    // Construct using raft.server.proto.PBRaftPersistentMeta.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      term_ = 0;

      votedFor_ = "";

      commitIndex_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return raft.server.proto.Commands.internal_static_raft_server_proto_PBRaftPersistentMeta_descriptor;
    }

    public raft.server.proto.PBRaftPersistentMeta getDefaultInstanceForType() {
      return raft.server.proto.PBRaftPersistentMeta.getDefaultInstance();
    }

    public raft.server.proto.PBRaftPersistentMeta build() {
      raft.server.proto.PBRaftPersistentMeta result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public raft.server.proto.PBRaftPersistentMeta buildPartial() {
      raft.server.proto.PBRaftPersistentMeta result = new raft.server.proto.PBRaftPersistentMeta(this);
      result.term_ = term_;
      result.votedFor_ = votedFor_;
      result.commitIndex_ = commitIndex_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof raft.server.proto.PBRaftPersistentMeta) {
        return mergeFrom((raft.server.proto.PBRaftPersistentMeta)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(raft.server.proto.PBRaftPersistentMeta other) {
      if (other == raft.server.proto.PBRaftPersistentMeta.getDefaultInstance()) return this;
      if (other.getTerm() != 0) {
        setTerm(other.getTerm());
      }
      if (!other.getVotedFor().isEmpty()) {
        votedFor_ = other.votedFor_;
        onChanged();
      }
      if (other.getCommitIndex() != 0) {
        setCommitIndex(other.getCommitIndex());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      raft.server.proto.PBRaftPersistentMeta parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (raft.server.proto.PBRaftPersistentMeta) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int term_ ;
    /**
     * <code>optional int32 term = 1;</code>
     */
    public int getTerm() {
      return term_;
    }
    /**
     * <code>optional int32 term = 1;</code>
     */
    public Builder setTerm(int value) {
      
      term_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 term = 1;</code>
     */
    public Builder clearTerm() {
      
      term_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object votedFor_ = "";
    /**
     * <code>optional string votedFor = 2;</code>
     */
    public java.lang.String getVotedFor() {
      java.lang.Object ref = votedFor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        votedFor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string votedFor = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVotedForBytes() {
      java.lang.Object ref = votedFor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        votedFor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string votedFor = 2;</code>
     */
    public Builder setVotedFor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      votedFor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string votedFor = 2;</code>
     */
    public Builder clearVotedFor() {
      
      votedFor_ = getDefaultInstance().getVotedFor();
      onChanged();
      return this;
    }
    /**
     * <code>optional string votedFor = 2;</code>
     */
    public Builder setVotedForBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      votedFor_ = value;
      onChanged();
      return this;
    }

    private int commitIndex_ ;
    /**
     * <code>optional int32 commitIndex = 3;</code>
     */
    public int getCommitIndex() {
      return commitIndex_;
    }
    /**
     * <code>optional int32 commitIndex = 3;</code>
     */
    public Builder setCommitIndex(int value) {
      
      commitIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 commitIndex = 3;</code>
     */
    public Builder clearCommitIndex() {
      
      commitIndex_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:raft.server.proto.PBRaftPersistentMeta)
  }

  // @@protoc_insertion_point(class_scope:raft.server.proto.PBRaftPersistentMeta)
  private static final raft.server.proto.PBRaftPersistentMeta DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new raft.server.proto.PBRaftPersistentMeta();
  }

  public static raft.server.proto.PBRaftPersistentMeta getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PBRaftPersistentMeta>
      PARSER = new com.google.protobuf.AbstractParser<PBRaftPersistentMeta>() {
    public PBRaftPersistentMeta parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBRaftPersistentMeta(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PBRaftPersistentMeta> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PBRaftPersistentMeta> getParserForType() {
    return PARSER;
  }

  public raft.server.proto.PBRaftPersistentMeta getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

