// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package raft.server.proto;

/**
 * Protobuf type {@code raft.server.proto.RaftCommand}
 */
public  final class RaftCommand extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:raft.server.proto.RaftCommand)
    RaftCommandOrBuilder {
  // Use RaftCommand.newBuilder() to construct.
  private RaftCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RaftCommand() {
    type_ = 0;
    from_ = "";
    to_ = "";
    term_ = 0L;
    prevLogIndex_ = 0L;
    prevLogTerm_ = 0L;
    matchIndex_ = 0L;
    leaderCommit_ = 0L;
    success_ = false;
    entries_ = java.util.Collections.emptyList();
    leaderId_ = "";
    lastLogIndex_ = 0L;
    lastLogTerm_ = 0L;
    voteGranted_ = false;
    leaderHint_ = "";
    forceElection_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RaftCommand(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            from_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            to_ = s;
            break;
          }
          case 32: {

            term_ = input.readInt64();
            break;
          }
          case 40: {

            prevLogIndex_ = input.readInt64();
            break;
          }
          case 48: {

            prevLogTerm_ = input.readInt64();
            break;
          }
          case 56: {

            matchIndex_ = input.readInt64();
            break;
          }
          case 64: {

            leaderCommit_ = input.readInt64();
            break;
          }
          case 72: {

            success_ = input.readBool();
            break;
          }
          case 82: {
            if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
              entries_ = new java.util.ArrayList<raft.server.proto.LogEntry>();
              mutable_bitField0_ |= 0x00000200;
            }
            entries_.add(
                input.readMessage(raft.server.proto.LogEntry.parser(), extensionRegistry));
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            leaderId_ = s;
            break;
          }
          case 96: {

            lastLogIndex_ = input.readInt64();
            break;
          }
          case 104: {

            lastLogTerm_ = input.readInt64();
            break;
          }
          case 112: {

            voteGranted_ = input.readBool();
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            leaderHint_ = s;
            break;
          }
          case 128: {

            forceElection_ = input.readBool();
            break;
          }
          case 138: {
            raft.server.proto.LogSnapshot.Builder subBuilder = null;
            if (snapshot_ != null) {
              subBuilder = snapshot_.toBuilder();
            }
            snapshot_ = input.readMessage(raft.server.proto.LogSnapshot.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(snapshot_);
              snapshot_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
        entries_ = java.util.Collections.unmodifiableList(entries_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return raft.server.proto.Commands.internal_static_raft_server_proto_RaftCommand_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return raft.server.proto.Commands.internal_static_raft_server_proto_RaftCommand_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            raft.server.proto.RaftCommand.class, raft.server.proto.RaftCommand.Builder.class);
  }

  /**
   * Protobuf enum {@code raft.server.proto.RaftCommand.CmdType}
   */
  public enum CmdType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NONE = 0;</code>
     */
    NONE(0),
    /**
     * <code>REQUEST_VOTE = 1;</code>
     */
    REQUEST_VOTE(1),
    /**
     * <code>REQUEST_VOTE_RESP = 2;</code>
     */
    REQUEST_VOTE_RESP(2),
    /**
     * <code>APPEND_ENTRIES = 3;</code>
     */
    APPEND_ENTRIES(3),
    /**
     * <code>APPEND_ENTRIES_RESP = 4;</code>
     */
    APPEND_ENTRIES_RESP(4),
    /**
     * <code>ADD_SERVER = 5;</code>
     */
    ADD_SERVER(5),
    /**
     * <code>ADD_SERVER_RESP = 6;</code>
     */
    ADD_SERVER_RESP(6),
    /**
     * <code>REMOVE_SERVER = 7;</code>
     */
    REMOVE_SERVER(7),
    /**
     * <code>REMOVE_SERVER_RESP = 8;</code>
     */
    REMOVE_SERVER_RESP(8),
    /**
     * <code>PING = 9;</code>
     */
    PING(9),
    /**
     * <code>PONG = 10;</code>
     */
    PONG(10),
    /**
     * <code>TIMEOUT_NOW = 11;</code>
     */
    TIMEOUT_NOW(11),
    /**
     * <code>TRANSFER_LEADER = 12;</code>
     */
    TRANSFER_LEADER(12),
    /**
     * <code>SNAPSHOT = 13;</code>
     */
    SNAPSHOT(13),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NONE = 0;</code>
     */
    public static final int NONE_VALUE = 0;
    /**
     * <code>REQUEST_VOTE = 1;</code>
     */
    public static final int REQUEST_VOTE_VALUE = 1;
    /**
     * <code>REQUEST_VOTE_RESP = 2;</code>
     */
    public static final int REQUEST_VOTE_RESP_VALUE = 2;
    /**
     * <code>APPEND_ENTRIES = 3;</code>
     */
    public static final int APPEND_ENTRIES_VALUE = 3;
    /**
     * <code>APPEND_ENTRIES_RESP = 4;</code>
     */
    public static final int APPEND_ENTRIES_RESP_VALUE = 4;
    /**
     * <code>ADD_SERVER = 5;</code>
     */
    public static final int ADD_SERVER_VALUE = 5;
    /**
     * <code>ADD_SERVER_RESP = 6;</code>
     */
    public static final int ADD_SERVER_RESP_VALUE = 6;
    /**
     * <code>REMOVE_SERVER = 7;</code>
     */
    public static final int REMOVE_SERVER_VALUE = 7;
    /**
     * <code>REMOVE_SERVER_RESP = 8;</code>
     */
    public static final int REMOVE_SERVER_RESP_VALUE = 8;
    /**
     * <code>PING = 9;</code>
     */
    public static final int PING_VALUE = 9;
    /**
     * <code>PONG = 10;</code>
     */
    public static final int PONG_VALUE = 10;
    /**
     * <code>TIMEOUT_NOW = 11;</code>
     */
    public static final int TIMEOUT_NOW_VALUE = 11;
    /**
     * <code>TRANSFER_LEADER = 12;</code>
     */
    public static final int TRANSFER_LEADER_VALUE = 12;
    /**
     * <code>SNAPSHOT = 13;</code>
     */
    public static final int SNAPSHOT_VALUE = 13;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CmdType valueOf(int value) {
      return forNumber(value);
    }

    public static CmdType forNumber(int value) {
      switch (value) {
        case 0: return NONE;
        case 1: return REQUEST_VOTE;
        case 2: return REQUEST_VOTE_RESP;
        case 3: return APPEND_ENTRIES;
        case 4: return APPEND_ENTRIES_RESP;
        case 5: return ADD_SERVER;
        case 6: return ADD_SERVER_RESP;
        case 7: return REMOVE_SERVER;
        case 8: return REMOVE_SERVER_RESP;
        case 9: return PING;
        case 10: return PONG;
        case 11: return TIMEOUT_NOW;
        case 12: return TRANSFER_LEADER;
        case 13: return SNAPSHOT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CmdType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CmdType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CmdType>() {
            public CmdType findValueByNumber(int number) {
              return CmdType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return raft.server.proto.RaftCommand.getDescriptor().getEnumTypes().get(0);
    }

    private static final CmdType[] VALUES = values();

    public static CmdType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CmdType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:raft.server.proto.RaftCommand.CmdType)
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>optional .raft.server.proto.RaftCommand.CmdType type = 1;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>optional .raft.server.proto.RaftCommand.CmdType type = 1;</code>
   */
  public raft.server.proto.RaftCommand.CmdType getType() {
    raft.server.proto.RaftCommand.CmdType result = raft.server.proto.RaftCommand.CmdType.valueOf(type_);
    return result == null ? raft.server.proto.RaftCommand.CmdType.UNRECOGNIZED : result;
  }

  public static final int FROM_FIELD_NUMBER = 2;
  private volatile java.lang.Object from_;
  /**
   * <code>optional string from = 2;</code>
   */
  public java.lang.String getFrom() {
    java.lang.Object ref = from_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      from_ = s;
      return s;
    }
  }
  /**
   * <code>optional string from = 2;</code>
   */
  public com.google.protobuf.ByteString
      getFromBytes() {
    java.lang.Object ref = from_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      from_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TO_FIELD_NUMBER = 3;
  private volatile java.lang.Object to_;
  /**
   * <code>optional string to = 3;</code>
   */
  public java.lang.String getTo() {
    java.lang.Object ref = to_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      to_ = s;
      return s;
    }
  }
  /**
   * <code>optional string to = 3;</code>
   */
  public com.google.protobuf.ByteString
      getToBytes() {
    java.lang.Object ref = to_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      to_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TERM_FIELD_NUMBER = 4;
  private long term_;
  /**
   * <code>optional int64 term = 4;</code>
   */
  public long getTerm() {
    return term_;
  }

  public static final int PREV_LOG_INDEX_FIELD_NUMBER = 5;
  private long prevLogIndex_;
  /**
   * <code>optional int64 prev_log_index = 5;</code>
   */
  public long getPrevLogIndex() {
    return prevLogIndex_;
  }

  public static final int PREV_LOG_TERM_FIELD_NUMBER = 6;
  private long prevLogTerm_;
  /**
   * <code>optional int64 prev_log_term = 6;</code>
   */
  public long getPrevLogTerm() {
    return prevLogTerm_;
  }

  public static final int MATCH_INDEX_FIELD_NUMBER = 7;
  private long matchIndex_;
  /**
   * <code>optional int64 match_index = 7;</code>
   */
  public long getMatchIndex() {
    return matchIndex_;
  }

  public static final int LEADER_COMMIT_FIELD_NUMBER = 8;
  private long leaderCommit_;
  /**
   * <code>optional int64 leader_commit = 8;</code>
   */
  public long getLeaderCommit() {
    return leaderCommit_;
  }

  public static final int SUCCESS_FIELD_NUMBER = 9;
  private boolean success_;
  /**
   * <code>optional bool success = 9;</code>
   */
  public boolean getSuccess() {
    return success_;
  }

  public static final int ENTRIES_FIELD_NUMBER = 10;
  private java.util.List<raft.server.proto.LogEntry> entries_;
  /**
   * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
   */
  public java.util.List<raft.server.proto.LogEntry> getEntriesList() {
    return entries_;
  }
  /**
   * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
   */
  public java.util.List<? extends raft.server.proto.LogEntryOrBuilder> 
      getEntriesOrBuilderList() {
    return entries_;
  }
  /**
   * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
   */
  public int getEntriesCount() {
    return entries_.size();
  }
  /**
   * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
   */
  public raft.server.proto.LogEntry getEntries(int index) {
    return entries_.get(index);
  }
  /**
   * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
   */
  public raft.server.proto.LogEntryOrBuilder getEntriesOrBuilder(
      int index) {
    return entries_.get(index);
  }

  public static final int LEADER_ID_FIELD_NUMBER = 11;
  private volatile java.lang.Object leaderId_;
  /**
   * <code>optional string leader_id = 11;</code>
   */
  public java.lang.String getLeaderId() {
    java.lang.Object ref = leaderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      leaderId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string leader_id = 11;</code>
   */
  public com.google.protobuf.ByteString
      getLeaderIdBytes() {
    java.lang.Object ref = leaderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      leaderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAST_LOG_INDEX_FIELD_NUMBER = 12;
  private long lastLogIndex_;
  /**
   * <code>optional int64 last_log_index = 12;</code>
   */
  public long getLastLogIndex() {
    return lastLogIndex_;
  }

  public static final int LAST_LOG_TERM_FIELD_NUMBER = 13;
  private long lastLogTerm_;
  /**
   * <code>optional int64 last_log_term = 13;</code>
   */
  public long getLastLogTerm() {
    return lastLogTerm_;
  }

  public static final int VOTE_GRANTED_FIELD_NUMBER = 14;
  private boolean voteGranted_;
  /**
   * <code>optional bool vote_granted = 14;</code>
   */
  public boolean getVoteGranted() {
    return voteGranted_;
  }

  public static final int LEADER_HINT_FIELD_NUMBER = 15;
  private volatile java.lang.Object leaderHint_;
  /**
   * <code>optional string leader_hint = 15;</code>
   */
  public java.lang.String getLeaderHint() {
    java.lang.Object ref = leaderHint_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      leaderHint_ = s;
      return s;
    }
  }
  /**
   * <code>optional string leader_hint = 15;</code>
   */
  public com.google.protobuf.ByteString
      getLeaderHintBytes() {
    java.lang.Object ref = leaderHint_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      leaderHint_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FORCE_ELECTION_FIELD_NUMBER = 16;
  private boolean forceElection_;
  /**
   * <code>optional bool force_election = 16;</code>
   */
  public boolean getForceElection() {
    return forceElection_;
  }

  public static final int SNAPSHOT_FIELD_NUMBER = 17;
  private raft.server.proto.LogSnapshot snapshot_;
  /**
   * <code>optional .raft.server.proto.LogSnapshot snapshot = 17;</code>
   */
  public boolean hasSnapshot() {
    return snapshot_ != null;
  }
  /**
   * <code>optional .raft.server.proto.LogSnapshot snapshot = 17;</code>
   */
  public raft.server.proto.LogSnapshot getSnapshot() {
    return snapshot_ == null ? raft.server.proto.LogSnapshot.getDefaultInstance() : snapshot_;
  }
  /**
   * <code>optional .raft.server.proto.LogSnapshot snapshot = 17;</code>
   */
  public raft.server.proto.LogSnapshotOrBuilder getSnapshotOrBuilder() {
    return getSnapshot();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != raft.server.proto.RaftCommand.CmdType.NONE.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (!getFromBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, from_);
    }
    if (!getToBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, to_);
    }
    if (term_ != 0L) {
      output.writeInt64(4, term_);
    }
    if (prevLogIndex_ != 0L) {
      output.writeInt64(5, prevLogIndex_);
    }
    if (prevLogTerm_ != 0L) {
      output.writeInt64(6, prevLogTerm_);
    }
    if (matchIndex_ != 0L) {
      output.writeInt64(7, matchIndex_);
    }
    if (leaderCommit_ != 0L) {
      output.writeInt64(8, leaderCommit_);
    }
    if (success_ != false) {
      output.writeBool(9, success_);
    }
    for (int i = 0; i < entries_.size(); i++) {
      output.writeMessage(10, entries_.get(i));
    }
    if (!getLeaderIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, leaderId_);
    }
    if (lastLogIndex_ != 0L) {
      output.writeInt64(12, lastLogIndex_);
    }
    if (lastLogTerm_ != 0L) {
      output.writeInt64(13, lastLogTerm_);
    }
    if (voteGranted_ != false) {
      output.writeBool(14, voteGranted_);
    }
    if (!getLeaderHintBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, leaderHint_);
    }
    if (forceElection_ != false) {
      output.writeBool(16, forceElection_);
    }
    if (snapshot_ != null) {
      output.writeMessage(17, getSnapshot());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != raft.server.proto.RaftCommand.CmdType.NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (!getFromBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, from_);
    }
    if (!getToBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, to_);
    }
    if (term_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, term_);
    }
    if (prevLogIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, prevLogIndex_);
    }
    if (prevLogTerm_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, prevLogTerm_);
    }
    if (matchIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, matchIndex_);
    }
    if (leaderCommit_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, leaderCommit_);
    }
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, success_);
    }
    for (int i = 0; i < entries_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, entries_.get(i));
    }
    if (!getLeaderIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, leaderId_);
    }
    if (lastLogIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, lastLogIndex_);
    }
    if (lastLogTerm_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(13, lastLogTerm_);
    }
    if (voteGranted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(14, voteGranted_);
    }
    if (!getLeaderHintBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, leaderHint_);
    }
    if (forceElection_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(16, forceElection_);
    }
    if (snapshot_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(17, getSnapshot());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof raft.server.proto.RaftCommand)) {
      return super.equals(obj);
    }
    raft.server.proto.RaftCommand other = (raft.server.proto.RaftCommand) obj;

    boolean result = true;
    result = result && type_ == other.type_;
    result = result && getFrom()
        .equals(other.getFrom());
    result = result && getTo()
        .equals(other.getTo());
    result = result && (getTerm()
        == other.getTerm());
    result = result && (getPrevLogIndex()
        == other.getPrevLogIndex());
    result = result && (getPrevLogTerm()
        == other.getPrevLogTerm());
    result = result && (getMatchIndex()
        == other.getMatchIndex());
    result = result && (getLeaderCommit()
        == other.getLeaderCommit());
    result = result && (getSuccess()
        == other.getSuccess());
    result = result && getEntriesList()
        .equals(other.getEntriesList());
    result = result && getLeaderId()
        .equals(other.getLeaderId());
    result = result && (getLastLogIndex()
        == other.getLastLogIndex());
    result = result && (getLastLogTerm()
        == other.getLastLogTerm());
    result = result && (getVoteGranted()
        == other.getVoteGranted());
    result = result && getLeaderHint()
        .equals(other.getLeaderHint());
    result = result && (getForceElection()
        == other.getForceElection());
    result = result && (hasSnapshot() == other.hasSnapshot());
    if (hasSnapshot()) {
      result = result && getSnapshot()
          .equals(other.getSnapshot());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + FROM_FIELD_NUMBER;
    hash = (53 * hash) + getFrom().hashCode();
    hash = (37 * hash) + TO_FIELD_NUMBER;
    hash = (53 * hash) + getTo().hashCode();
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTerm());
    hash = (37 * hash) + PREV_LOG_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPrevLogIndex());
    hash = (37 * hash) + PREV_LOG_TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPrevLogTerm());
    hash = (37 * hash) + MATCH_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMatchIndex());
    hash = (37 * hash) + LEADER_COMMIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLeaderCommit());
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    if (getEntriesCount() > 0) {
      hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
      hash = (53 * hash) + getEntriesList().hashCode();
    }
    hash = (37 * hash) + LEADER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getLeaderId().hashCode();
    hash = (37 * hash) + LAST_LOG_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastLogIndex());
    hash = (37 * hash) + LAST_LOG_TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastLogTerm());
    hash = (37 * hash) + VOTE_GRANTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getVoteGranted());
    hash = (37 * hash) + LEADER_HINT_FIELD_NUMBER;
    hash = (53 * hash) + getLeaderHint().hashCode();
    hash = (37 * hash) + FORCE_ELECTION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getForceElection());
    if (hasSnapshot()) {
      hash = (37 * hash) + SNAPSHOT_FIELD_NUMBER;
      hash = (53 * hash) + getSnapshot().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static raft.server.proto.RaftCommand parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static raft.server.proto.RaftCommand parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static raft.server.proto.RaftCommand parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static raft.server.proto.RaftCommand parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static raft.server.proto.RaftCommand parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static raft.server.proto.RaftCommand parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static raft.server.proto.RaftCommand parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static raft.server.proto.RaftCommand parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static raft.server.proto.RaftCommand parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static raft.server.proto.RaftCommand parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(raft.server.proto.RaftCommand prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code raft.server.proto.RaftCommand}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:raft.server.proto.RaftCommand)
      raft.server.proto.RaftCommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return raft.server.proto.Commands.internal_static_raft_server_proto_RaftCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return raft.server.proto.Commands.internal_static_raft_server_proto_RaftCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              raft.server.proto.RaftCommand.class, raft.server.proto.RaftCommand.Builder.class);
    }

    // Construct using raft.server.proto.RaftCommand.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEntriesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      type_ = 0;

      from_ = "";

      to_ = "";

      term_ = 0L;

      prevLogIndex_ = 0L;

      prevLogTerm_ = 0L;

      matchIndex_ = 0L;

      leaderCommit_ = 0L;

      success_ = false;

      if (entriesBuilder_ == null) {
        entries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
      } else {
        entriesBuilder_.clear();
      }
      leaderId_ = "";

      lastLogIndex_ = 0L;

      lastLogTerm_ = 0L;

      voteGranted_ = false;

      leaderHint_ = "";

      forceElection_ = false;

      if (snapshotBuilder_ == null) {
        snapshot_ = null;
      } else {
        snapshot_ = null;
        snapshotBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return raft.server.proto.Commands.internal_static_raft_server_proto_RaftCommand_descriptor;
    }

    public raft.server.proto.RaftCommand getDefaultInstanceForType() {
      return raft.server.proto.RaftCommand.getDefaultInstance();
    }

    public raft.server.proto.RaftCommand build() {
      raft.server.proto.RaftCommand result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public raft.server.proto.RaftCommand buildPartial() {
      raft.server.proto.RaftCommand result = new raft.server.proto.RaftCommand(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.type_ = type_;
      result.from_ = from_;
      result.to_ = to_;
      result.term_ = term_;
      result.prevLogIndex_ = prevLogIndex_;
      result.prevLogTerm_ = prevLogTerm_;
      result.matchIndex_ = matchIndex_;
      result.leaderCommit_ = leaderCommit_;
      result.success_ = success_;
      if (entriesBuilder_ == null) {
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          entries_ = java.util.Collections.unmodifiableList(entries_);
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.entries_ = entries_;
      } else {
        result.entries_ = entriesBuilder_.build();
      }
      result.leaderId_ = leaderId_;
      result.lastLogIndex_ = lastLogIndex_;
      result.lastLogTerm_ = lastLogTerm_;
      result.voteGranted_ = voteGranted_;
      result.leaderHint_ = leaderHint_;
      result.forceElection_ = forceElection_;
      if (snapshotBuilder_ == null) {
        result.snapshot_ = snapshot_;
      } else {
        result.snapshot_ = snapshotBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof raft.server.proto.RaftCommand) {
        return mergeFrom((raft.server.proto.RaftCommand)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(raft.server.proto.RaftCommand other) {
      if (other == raft.server.proto.RaftCommand.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getFrom().isEmpty()) {
        from_ = other.from_;
        onChanged();
      }
      if (!other.getTo().isEmpty()) {
        to_ = other.to_;
        onChanged();
      }
      if (other.getTerm() != 0L) {
        setTerm(other.getTerm());
      }
      if (other.getPrevLogIndex() != 0L) {
        setPrevLogIndex(other.getPrevLogIndex());
      }
      if (other.getPrevLogTerm() != 0L) {
        setPrevLogTerm(other.getPrevLogTerm());
      }
      if (other.getMatchIndex() != 0L) {
        setMatchIndex(other.getMatchIndex());
      }
      if (other.getLeaderCommit() != 0L) {
        setLeaderCommit(other.getLeaderCommit());
      }
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (entriesBuilder_ == null) {
        if (!other.entries_.isEmpty()) {
          if (entries_.isEmpty()) {
            entries_ = other.entries_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensureEntriesIsMutable();
            entries_.addAll(other.entries_);
          }
          onChanged();
        }
      } else {
        if (!other.entries_.isEmpty()) {
          if (entriesBuilder_.isEmpty()) {
            entriesBuilder_.dispose();
            entriesBuilder_ = null;
            entries_ = other.entries_;
            bitField0_ = (bitField0_ & ~0x00000200);
            entriesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEntriesFieldBuilder() : null;
          } else {
            entriesBuilder_.addAllMessages(other.entries_);
          }
        }
      }
      if (!other.getLeaderId().isEmpty()) {
        leaderId_ = other.leaderId_;
        onChanged();
      }
      if (other.getLastLogIndex() != 0L) {
        setLastLogIndex(other.getLastLogIndex());
      }
      if (other.getLastLogTerm() != 0L) {
        setLastLogTerm(other.getLastLogTerm());
      }
      if (other.getVoteGranted() != false) {
        setVoteGranted(other.getVoteGranted());
      }
      if (!other.getLeaderHint().isEmpty()) {
        leaderHint_ = other.leaderHint_;
        onChanged();
      }
      if (other.getForceElection() != false) {
        setForceElection(other.getForceElection());
      }
      if (other.hasSnapshot()) {
        mergeSnapshot(other.getSnapshot());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      raft.server.proto.RaftCommand parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (raft.server.proto.RaftCommand) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>optional .raft.server.proto.RaftCommand.CmdType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .raft.server.proto.RaftCommand.CmdType type = 1;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .raft.server.proto.RaftCommand.CmdType type = 1;</code>
     */
    public raft.server.proto.RaftCommand.CmdType getType() {
      raft.server.proto.RaftCommand.CmdType result = raft.server.proto.RaftCommand.CmdType.valueOf(type_);
      return result == null ? raft.server.proto.RaftCommand.CmdType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .raft.server.proto.RaftCommand.CmdType type = 1;</code>
     */
    public Builder setType(raft.server.proto.RaftCommand.CmdType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .raft.server.proto.RaftCommand.CmdType type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object from_ = "";
    /**
     * <code>optional string from = 2;</code>
     */
    public java.lang.String getFrom() {
      java.lang.Object ref = from_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        from_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string from = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string from = 2;</code>
     */
    public Builder setFrom(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      from_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string from = 2;</code>
     */
    public Builder clearFrom() {
      
      from_ = getDefaultInstance().getFrom();
      onChanged();
      return this;
    }
    /**
     * <code>optional string from = 2;</code>
     */
    public Builder setFromBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      from_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object to_ = "";
    /**
     * <code>optional string to = 3;</code>
     */
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string to = 3;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string to = 3;</code>
     */
    public Builder setTo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      to_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string to = 3;</code>
     */
    public Builder clearTo() {
      
      to_ = getDefaultInstance().getTo();
      onChanged();
      return this;
    }
    /**
     * <code>optional string to = 3;</code>
     */
    public Builder setToBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      to_ = value;
      onChanged();
      return this;
    }

    private long term_ ;
    /**
     * <code>optional int64 term = 4;</code>
     */
    public long getTerm() {
      return term_;
    }
    /**
     * <code>optional int64 term = 4;</code>
     */
    public Builder setTerm(long value) {
      
      term_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 term = 4;</code>
     */
    public Builder clearTerm() {
      
      term_ = 0L;
      onChanged();
      return this;
    }

    private long prevLogIndex_ ;
    /**
     * <code>optional int64 prev_log_index = 5;</code>
     */
    public long getPrevLogIndex() {
      return prevLogIndex_;
    }
    /**
     * <code>optional int64 prev_log_index = 5;</code>
     */
    public Builder setPrevLogIndex(long value) {
      
      prevLogIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 prev_log_index = 5;</code>
     */
    public Builder clearPrevLogIndex() {
      
      prevLogIndex_ = 0L;
      onChanged();
      return this;
    }

    private long prevLogTerm_ ;
    /**
     * <code>optional int64 prev_log_term = 6;</code>
     */
    public long getPrevLogTerm() {
      return prevLogTerm_;
    }
    /**
     * <code>optional int64 prev_log_term = 6;</code>
     */
    public Builder setPrevLogTerm(long value) {
      
      prevLogTerm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 prev_log_term = 6;</code>
     */
    public Builder clearPrevLogTerm() {
      
      prevLogTerm_ = 0L;
      onChanged();
      return this;
    }

    private long matchIndex_ ;
    /**
     * <code>optional int64 match_index = 7;</code>
     */
    public long getMatchIndex() {
      return matchIndex_;
    }
    /**
     * <code>optional int64 match_index = 7;</code>
     */
    public Builder setMatchIndex(long value) {
      
      matchIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 match_index = 7;</code>
     */
    public Builder clearMatchIndex() {
      
      matchIndex_ = 0L;
      onChanged();
      return this;
    }

    private long leaderCommit_ ;
    /**
     * <code>optional int64 leader_commit = 8;</code>
     */
    public long getLeaderCommit() {
      return leaderCommit_;
    }
    /**
     * <code>optional int64 leader_commit = 8;</code>
     */
    public Builder setLeaderCommit(long value) {
      
      leaderCommit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 leader_commit = 8;</code>
     */
    public Builder clearLeaderCommit() {
      
      leaderCommit_ = 0L;
      onChanged();
      return this;
    }

    private boolean success_ ;
    /**
     * <code>optional bool success = 9;</code>
     */
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>optional bool success = 9;</code>
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool success = 9;</code>
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }

    private java.util.List<raft.server.proto.LogEntry> entries_ =
      java.util.Collections.emptyList();
    private void ensureEntriesIsMutable() {
      if (!((bitField0_ & 0x00000200) == 0x00000200)) {
        entries_ = new java.util.ArrayList<raft.server.proto.LogEntry>(entries_);
        bitField0_ |= 0x00000200;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        raft.server.proto.LogEntry, raft.server.proto.LogEntry.Builder, raft.server.proto.LogEntryOrBuilder> entriesBuilder_;

    /**
     * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
     */
    public java.util.List<raft.server.proto.LogEntry> getEntriesList() {
      if (entriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(entries_);
      } else {
        return entriesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
     */
    public int getEntriesCount() {
      if (entriesBuilder_ == null) {
        return entries_.size();
      } else {
        return entriesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
     */
    public raft.server.proto.LogEntry getEntries(int index) {
      if (entriesBuilder_ == null) {
        return entries_.get(index);
      } else {
        return entriesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
     */
    public Builder setEntries(
        int index, raft.server.proto.LogEntry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.set(index, value);
        onChanged();
      } else {
        entriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
     */
    public Builder setEntries(
        int index, raft.server.proto.LogEntry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.set(index, builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
     */
    public Builder addEntries(raft.server.proto.LogEntry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.add(value);
        onChanged();
      } else {
        entriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
     */
    public Builder addEntries(
        int index, raft.server.proto.LogEntry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.add(index, value);
        onChanged();
      } else {
        entriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
     */
    public Builder addEntries(
        raft.server.proto.LogEntry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.add(builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
     */
    public Builder addEntries(
        int index, raft.server.proto.LogEntry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.add(index, builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
     */
    public Builder addAllEntries(
        java.lang.Iterable<? extends raft.server.proto.LogEntry> values) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entries_);
        onChanged();
      } else {
        entriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
     */
    public Builder clearEntries() {
      if (entriesBuilder_ == null) {
        entries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
      } else {
        entriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
     */
    public Builder removeEntries(int index) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.remove(index);
        onChanged();
      } else {
        entriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
     */
    public raft.server.proto.LogEntry.Builder getEntriesBuilder(
        int index) {
      return getEntriesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
     */
    public raft.server.proto.LogEntryOrBuilder getEntriesOrBuilder(
        int index) {
      if (entriesBuilder_ == null) {
        return entries_.get(index);  } else {
        return entriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
     */
    public java.util.List<? extends raft.server.proto.LogEntryOrBuilder> 
         getEntriesOrBuilderList() {
      if (entriesBuilder_ != null) {
        return entriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(entries_);
      }
    }
    /**
     * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
     */
    public raft.server.proto.LogEntry.Builder addEntriesBuilder() {
      return getEntriesFieldBuilder().addBuilder(
          raft.server.proto.LogEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
     */
    public raft.server.proto.LogEntry.Builder addEntriesBuilder(
        int index) {
      return getEntriesFieldBuilder().addBuilder(
          index, raft.server.proto.LogEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
     */
    public java.util.List<raft.server.proto.LogEntry.Builder> 
         getEntriesBuilderList() {
      return getEntriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        raft.server.proto.LogEntry, raft.server.proto.LogEntry.Builder, raft.server.proto.LogEntryOrBuilder> 
        getEntriesFieldBuilder() {
      if (entriesBuilder_ == null) {
        entriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            raft.server.proto.LogEntry, raft.server.proto.LogEntry.Builder, raft.server.proto.LogEntryOrBuilder>(
                entries_,
                ((bitField0_ & 0x00000200) == 0x00000200),
                getParentForChildren(),
                isClean());
        entries_ = null;
      }
      return entriesBuilder_;
    }

    private java.lang.Object leaderId_ = "";
    /**
     * <code>optional string leader_id = 11;</code>
     */
    public java.lang.String getLeaderId() {
      java.lang.Object ref = leaderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leaderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string leader_id = 11;</code>
     */
    public com.google.protobuf.ByteString
        getLeaderIdBytes() {
      java.lang.Object ref = leaderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string leader_id = 11;</code>
     */
    public Builder setLeaderId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      leaderId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string leader_id = 11;</code>
     */
    public Builder clearLeaderId() {
      
      leaderId_ = getDefaultInstance().getLeaderId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string leader_id = 11;</code>
     */
    public Builder setLeaderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      leaderId_ = value;
      onChanged();
      return this;
    }

    private long lastLogIndex_ ;
    /**
     * <code>optional int64 last_log_index = 12;</code>
     */
    public long getLastLogIndex() {
      return lastLogIndex_;
    }
    /**
     * <code>optional int64 last_log_index = 12;</code>
     */
    public Builder setLastLogIndex(long value) {
      
      lastLogIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 last_log_index = 12;</code>
     */
    public Builder clearLastLogIndex() {
      
      lastLogIndex_ = 0L;
      onChanged();
      return this;
    }

    private long lastLogTerm_ ;
    /**
     * <code>optional int64 last_log_term = 13;</code>
     */
    public long getLastLogTerm() {
      return lastLogTerm_;
    }
    /**
     * <code>optional int64 last_log_term = 13;</code>
     */
    public Builder setLastLogTerm(long value) {
      
      lastLogTerm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 last_log_term = 13;</code>
     */
    public Builder clearLastLogTerm() {
      
      lastLogTerm_ = 0L;
      onChanged();
      return this;
    }

    private boolean voteGranted_ ;
    /**
     * <code>optional bool vote_granted = 14;</code>
     */
    public boolean getVoteGranted() {
      return voteGranted_;
    }
    /**
     * <code>optional bool vote_granted = 14;</code>
     */
    public Builder setVoteGranted(boolean value) {
      
      voteGranted_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool vote_granted = 14;</code>
     */
    public Builder clearVoteGranted() {
      
      voteGranted_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object leaderHint_ = "";
    /**
     * <code>optional string leader_hint = 15;</code>
     */
    public java.lang.String getLeaderHint() {
      java.lang.Object ref = leaderHint_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leaderHint_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string leader_hint = 15;</code>
     */
    public com.google.protobuf.ByteString
        getLeaderHintBytes() {
      java.lang.Object ref = leaderHint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderHint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string leader_hint = 15;</code>
     */
    public Builder setLeaderHint(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      leaderHint_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string leader_hint = 15;</code>
     */
    public Builder clearLeaderHint() {
      
      leaderHint_ = getDefaultInstance().getLeaderHint();
      onChanged();
      return this;
    }
    /**
     * <code>optional string leader_hint = 15;</code>
     */
    public Builder setLeaderHintBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      leaderHint_ = value;
      onChanged();
      return this;
    }

    private boolean forceElection_ ;
    /**
     * <code>optional bool force_election = 16;</code>
     */
    public boolean getForceElection() {
      return forceElection_;
    }
    /**
     * <code>optional bool force_election = 16;</code>
     */
    public Builder setForceElection(boolean value) {
      
      forceElection_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool force_election = 16;</code>
     */
    public Builder clearForceElection() {
      
      forceElection_ = false;
      onChanged();
      return this;
    }

    private raft.server.proto.LogSnapshot snapshot_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        raft.server.proto.LogSnapshot, raft.server.proto.LogSnapshot.Builder, raft.server.proto.LogSnapshotOrBuilder> snapshotBuilder_;
    /**
     * <code>optional .raft.server.proto.LogSnapshot snapshot = 17;</code>
     */
    public boolean hasSnapshot() {
      return snapshotBuilder_ != null || snapshot_ != null;
    }
    /**
     * <code>optional .raft.server.proto.LogSnapshot snapshot = 17;</code>
     */
    public raft.server.proto.LogSnapshot getSnapshot() {
      if (snapshotBuilder_ == null) {
        return snapshot_ == null ? raft.server.proto.LogSnapshot.getDefaultInstance() : snapshot_;
      } else {
        return snapshotBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .raft.server.proto.LogSnapshot snapshot = 17;</code>
     */
    public Builder setSnapshot(raft.server.proto.LogSnapshot value) {
      if (snapshotBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        snapshot_ = value;
        onChanged();
      } else {
        snapshotBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .raft.server.proto.LogSnapshot snapshot = 17;</code>
     */
    public Builder setSnapshot(
        raft.server.proto.LogSnapshot.Builder builderForValue) {
      if (snapshotBuilder_ == null) {
        snapshot_ = builderForValue.build();
        onChanged();
      } else {
        snapshotBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .raft.server.proto.LogSnapshot snapshot = 17;</code>
     */
    public Builder mergeSnapshot(raft.server.proto.LogSnapshot value) {
      if (snapshotBuilder_ == null) {
        if (snapshot_ != null) {
          snapshot_ =
            raft.server.proto.LogSnapshot.newBuilder(snapshot_).mergeFrom(value).buildPartial();
        } else {
          snapshot_ = value;
        }
        onChanged();
      } else {
        snapshotBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .raft.server.proto.LogSnapshot snapshot = 17;</code>
     */
    public Builder clearSnapshot() {
      if (snapshotBuilder_ == null) {
        snapshot_ = null;
        onChanged();
      } else {
        snapshot_ = null;
        snapshotBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .raft.server.proto.LogSnapshot snapshot = 17;</code>
     */
    public raft.server.proto.LogSnapshot.Builder getSnapshotBuilder() {
      
      onChanged();
      return getSnapshotFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .raft.server.proto.LogSnapshot snapshot = 17;</code>
     */
    public raft.server.proto.LogSnapshotOrBuilder getSnapshotOrBuilder() {
      if (snapshotBuilder_ != null) {
        return snapshotBuilder_.getMessageOrBuilder();
      } else {
        return snapshot_ == null ?
            raft.server.proto.LogSnapshot.getDefaultInstance() : snapshot_;
      }
    }
    /**
     * <code>optional .raft.server.proto.LogSnapshot snapshot = 17;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        raft.server.proto.LogSnapshot, raft.server.proto.LogSnapshot.Builder, raft.server.proto.LogSnapshotOrBuilder> 
        getSnapshotFieldBuilder() {
      if (snapshotBuilder_ == null) {
        snapshotBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            raft.server.proto.LogSnapshot, raft.server.proto.LogSnapshot.Builder, raft.server.proto.LogSnapshotOrBuilder>(
                getSnapshot(),
                getParentForChildren(),
                isClean());
        snapshot_ = null;
      }
      return snapshotBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:raft.server.proto.RaftCommand)
  }

  // @@protoc_insertion_point(class_scope:raft.server.proto.RaftCommand)
  private static final raft.server.proto.RaftCommand DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new raft.server.proto.RaftCommand();
  }

  public static raft.server.proto.RaftCommand getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RaftCommand>
      PARSER = new com.google.protobuf.AbstractParser<RaftCommand>() {
    public RaftCommand parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new RaftCommand(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RaftCommand> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RaftCommand> getParserForType() {
    return PARSER;
  }

  public raft.server.proto.RaftCommand getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

