// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package raft.server.proto;

public interface RaftCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:raft.server.proto.RaftCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.raft.server.proto.RaftCommand.CmdType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>.raft.server.proto.RaftCommand.CmdType type = 1;</code>
   */
  raft.server.proto.RaftCommand.CmdType getType();

  /**
   * <code>string from = 2;</code>
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 2;</code>
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>string to = 3;</code>
   */
  java.lang.String getTo();
  /**
   * <code>string to = 3;</code>
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <code>int32 term = 4;</code>
   */
  int getTerm();

  /**
   * <code>int32 prev_log_index = 5;</code>
   */
  int getPrevLogIndex();

  /**
   * <code>int32 prev_log_term = 6;</code>
   */
  int getPrevLogTerm();

  /**
   * <code>int32 match_index = 7;</code>
   */
  int getMatchIndex();

  /**
   * <code>int32 leader_commit = 8;</code>
   */
  int getLeaderCommit();

  /**
   * <code>bool success = 9;</code>
   */
  boolean getSuccess();

  /**
   * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
   */
  java.util.List<raft.server.proto.LogEntry> 
      getEntriesList();
  /**
   * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
   */
  raft.server.proto.LogEntry getEntries(int index);
  /**
   * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
   */
  java.util.List<? extends raft.server.proto.LogEntryOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
   */
  raft.server.proto.LogEntryOrBuilder getEntriesOrBuilder(
      int index);

  /**
   * <code>string leader_id = 11;</code>
   */
  java.lang.String getLeaderId();
  /**
   * <code>string leader_id = 11;</code>
   */
  com.google.protobuf.ByteString
      getLeaderIdBytes();

  /**
   * <code>int32 last_log_index = 12;</code>
   */
  int getLastLogIndex();

  /**
   * <code>int32 last_log_term = 13;</code>
   */
  int getLastLogTerm();

  /**
   * <code>bool vote_granted = 14;</code>
   */
  boolean getVoteGranted();

  /**
   * <code>string leader_hint = 15;</code>
   */
  java.lang.String getLeaderHint();
  /**
   * <code>string leader_hint = 15;</code>
   */
  com.google.protobuf.ByteString
      getLeaderHintBytes();

  /**
   * <code>bool force_election = 16;</code>
   */
  boolean getForceElection();

  /**
   * <code>.raft.server.proto.Snapshot snapshot = 17;</code>
   */
  boolean hasSnapshot();
  /**
   * <code>.raft.server.proto.Snapshot snapshot = 17;</code>
   */
  raft.server.proto.Snapshot getSnapshot();
  /**
   * <code>.raft.server.proto.Snapshot snapshot = 17;</code>
   */
  raft.server.proto.SnapshotOrBuilder getSnapshotOrBuilder();
}
