// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package raft.server.proto;

public interface RaftCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:raft.server.proto.RaftCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .raft.server.proto.RaftCommand.CmdType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>optional .raft.server.proto.RaftCommand.CmdType type = 1;</code>
   */
  raft.server.proto.RaftCommand.CmdType getType();

  /**
   * <code>optional string from = 2;</code>
   */
  java.lang.String getFrom();
  /**
   * <code>optional string from = 2;</code>
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>optional string to = 3;</code>
   */
  java.lang.String getTo();
  /**
   * <code>optional string to = 3;</code>
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <code>optional int64 term = 4;</code>
   */
  long getTerm();

  /**
   * <code>optional int64 prev_log_index = 5;</code>
   */
  long getPrevLogIndex();

  /**
   * <code>optional int64 prev_log_term = 6;</code>
   */
  long getPrevLogTerm();

  /**
   * <code>optional int64 match_index = 7;</code>
   */
  long getMatchIndex();

  /**
   * <code>optional int64 leader_commit = 8;</code>
   */
  long getLeaderCommit();

  /**
   * <code>optional bool success = 9;</code>
   */
  boolean getSuccess();

  /**
   * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
   */
  java.util.List<raft.server.proto.LogEntry> 
      getEntriesList();
  /**
   * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
   */
  raft.server.proto.LogEntry getEntries(int index);
  /**
   * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
   */
  java.util.List<? extends raft.server.proto.LogEntryOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .raft.server.proto.LogEntry entries = 10;</code>
   */
  raft.server.proto.LogEntryOrBuilder getEntriesOrBuilder(
      int index);

  /**
   * <code>optional string leader_id = 11;</code>
   */
  java.lang.String getLeaderId();
  /**
   * <code>optional string leader_id = 11;</code>
   */
  com.google.protobuf.ByteString
      getLeaderIdBytes();

  /**
   * <code>optional int64 last_log_index = 12;</code>
   */
  long getLastLogIndex();

  /**
   * <code>optional int64 last_log_term = 13;</code>
   */
  long getLastLogTerm();

  /**
   * <code>optional bool vote_granted = 14;</code>
   */
  boolean getVoteGranted();

  /**
   * <code>optional string leader_hint = 15;</code>
   */
  java.lang.String getLeaderHint();
  /**
   * <code>optional string leader_hint = 15;</code>
   */
  com.google.protobuf.ByteString
      getLeaderHintBytes();

  /**
   * <code>optional bool force_election = 16;</code>
   */
  boolean getForceElection();

  /**
   * <code>optional .raft.server.proto.LogSnapshot snapshot = 17;</code>
   */
  boolean hasSnapshot();
  /**
   * <code>optional .raft.server.proto.LogSnapshot snapshot = 17;</code>
   */
  raft.server.proto.LogSnapshot getSnapshot();
  /**
   * <code>optional .raft.server.proto.LogSnapshot snapshot = 17;</code>
   */
  raft.server.proto.LogSnapshotOrBuilder getSnapshotOrBuilder();
}
