// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package raft.server.proto;

public interface SnapshotOrBuilder extends
    // @@protoc_insertion_point(interface_extends:raft.server.proto.Snapshot)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>int32 index = 2;</code>
   */
  int getIndex();

  /**
   * <code>int32 term = 3;</code>
   */
  int getTerm();

  /**
   * <code>repeated string peer_ids = 4;</code>
   */
  java.util.List<java.lang.String>
      getPeerIdsList();
  /**
   * <code>repeated string peer_ids = 4;</code>
   */
  int getPeerIdsCount();
  /**
   * <code>repeated string peer_ids = 4;</code>
   */
  java.lang.String getPeerIds(int index);
  /**
   * <code>repeated string peer_ids = 4;</code>
   */
  com.google.protobuf.ByteString
      getPeerIdsBytes(int index);
}
